networks:
  dev:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: JobSpark1337
      POSTGRES_USER: Root
      POSTGRES_DB: JobSpark
    networks:
      - dev
    ports:
      - "5432:5432"