networks:
  dev:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: JobSpark1337
      POSTGRES_USER: Root
      POSTGRES_DB: JobSpark
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - dev